# Generated by Django 5.1.3 on 2025-04-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0004_remove_teacher_codewars_remove_teacher_github_and_more'),
        ('LessonPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='IlmiyIsh',
        ),
    ]
