# Generated by Django 5.1.3 on 2025-04-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonPlanner', '0002_rename_lesson_ilmiyish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilmiyish',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='ilmiyish',
            name='group',
        ),
        migrations.AddField(
            model_name='ilmiyish',
            name='file',
            field=models.FileField(blank=True, upload_to='ilmiy_ish/'),
        ),
    ]
