# Generated by Django 4.2.1 on 2023-05-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
