# Generated by Django 5.1.3 on 2025-04-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0002_remove_student_status'),
        ('LessonPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='University',
        ),
    ]
