# Generated by Django 5.1.3 on 2025-04-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0003_rename_course_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='codewars',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='github',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='type',
        ),
    ]
