# Generated by Django 5.1.3 on 2025-04-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0004_remove_teacher_codewars_remove_teacher_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='codewars',
        ),
        migrations.RemoveField(
            model_name='student',
            name='github',
        ),
    ]
